# Generated by Django 2.2.6 on 2019-11-13 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_type', models.CharField(choices=[('S', 'Student'), ('PR', 'PR')], max_length=2)),
                ('current_cgpa', models.IntegerField()),
                ('dob', models.DateField()),
                ('contact_number', models.CharField(max_length=10)),
                ('personal_email', models.CharField(max_length=256)),
                ('branch_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.BranchYear')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
