# Generated by Django 2.2.6 on 2019-11-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchyear',
            name='group',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='branchyear',
            name='branch',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='branchyear',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
