# Generated by Django 2.2.3 on 2019-11-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='u_type',
            field=models.CharField(choices=[('S', 'Student'), ('PR', 'PR')], default='S', max_length=2),
        ),
    ]
